### ISSUE TITLE
Please, explain how does copying memory on each draw operation stops crashing

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#152]
https://github.com/jcupitt/ruby-vips/blob/4d9340ff6aa19c6f29300a198994b03948b01893/lib/vips.rb#L416-L417

I want to understand how ruby-vips works to make smth about my code that does lots of drawing and so leaks a lot.

**Comment by Nakilon** [comment]
For example, I disabled this line

https://github.com/jcupitt/ruby-vips/blob/143e4133af85aefff4bcecde42f30c833195904c/lib/vips/operation.rb#L148

for `draw_line` and `draw_circle`, and it didn't crash.

**Comment by jcupitt** [comment]
Hello @Nakilon, when you draw on a computed image, libvips has to allocate some memory, render the image into that memory, then adjust the image structure so that it refers to the memory area and not the pipeline.

For example:

```ruby
a = Vips::Image.new_from_file "x.jpg"
b = a + 10
c = b
```

So `b` is now the head of a pipeline of delayed computations and `c` is a reference to it. But if you now do:

```ruby
b.draw_line 255, 10, 10, 110, 110
```

Now `b` has been changed internally to be a memory area and no longer references `a`, but `c` is still referencing the delayed computation. If you try and use `c`, you'll probably get a crash, or at least strange behaviour. 

It can be hard to see when images are being shared like this, especially in a threaded program with the libvips cache turned on. You need to `.copy()` before using any of the draw operations if there's any chance there could be another reference to the image somewhere. 

I think we were talking a few months ago about a better way to handle this. It would be much faster to make a new block, called `mutable` or `destructive`, that you used like this:

```ruby
b = a.mutable do |x|
    x.draw_line 255, 10, 10, 100, 100
    x.draw_circle ...
end
```

With some kind of lock so that draw operations could only be used inside a `mutable` block, and the `mutable` does the copy only once and passes the copied image in.

**Comment by jcupitt** [comment]
Perhaps as a first step we could add a `nocopy` optional argument? It would disable the extra copy if set `true`. We could then implement the `!` versions, and document it as the caller's responsibility to call `.copy` before the first `!`.

It's not really a memory leak, it's just very heavy memory use that the Ruby GC does not know about.

**Comment by jcupitt** [comment]
Here's a branch that adds `!` operators:

https://github.com/jcupitt/ruby-vips/tree/add-destructive

Before:

```ruby
require 'vips'

Vips::leak_set true

im = Vips::Image.new_from_file ARGV[0]

im = im.copy
(0..im.width).step(10) do |i|
  im = im.draw_line 255, i, 0, 0, im.height - i
  im = im.draw_line 255, i, 0, im.width, i
  im = im.draw_line 255, i, im.height, 0, i
  im = im.draw_line 255, i, im.height, im.width, im.height - i
end

im.write_to_file ARGV[1]
```

```
$ time ruby lines.rb ~/pics/k2.jpg x.jpg
memory: high-water mark 425.07 MB
real	0m2.360s
user	0m3.782s
sys	0m0.875s
```

If I change it to:


```ruby
require 'vips'

Vips::leak_set true

im = Vips::Image.new_from_file ARGV[0]

im = im.copy
(0..im.width).step(10) do |i|
  im.draw_line! 255, i, 0, 0, im.height - i
  im.draw_line! 255, i, 0, im.width, i
  im.draw_line! 255, i, im.height, 0, i
  im.draw_line! 255, i, im.height, im.width, im.height - i
end

im.write_to_file ARGV[1]
```

I see:

```
$ time ruby lines.rb ~/pics/k2.jpg x.jpg
memory: high-water mark 19.32 MB
real	0m0.966s
user	0m0.954s
sys	0m0.098s
```

Still not especially quick, but much better memory use. 

It's still possible to write a program that will crash, which seems bad.

**Comment by jcupitt** [comment]
See https://github.com/libvips/ruby-vips/issues/139
