### ISSUE TITLE
Sharing Libvips & AWS Lambda Work

### ISSUE THREAD

**Issue by metaskills** [libvips/ruby-vips#194]
First, thanks so much for the work here and making it easy to use either ImageMagick or Libvips with Ruby. I wanted to share my Lambda Layer work that makes it easy to use `ImageProcessing::Vips` with AWS Lambda via the ruby-vips gem.

https://github.com/customink/ruby-vips-lambda

If people are interested in moving off Heroku to AWS Lambda via something like the Lamby gem. https://github.com/customink/lamby

**Comment by jcupitt** [comment]
Oh, that's nice @metaskills, thanks for sharing. @janko did all the great work on the imageprocessing gem.

I keep some Dockerfiles here:

https://github.com/jcupitt/docker-builds

I have a couple for AWS which are close to what you have:

https://github.com/jcupitt/docker-builds/blob/master/libvips-amazonlinux-2018.03/Dockerfile

Rather than cloning libvips, I would `wget` one of the release tarballs and build that. You then won't need `gtk-doc` or `gobject-introspection`. You might also need to tune the list of dependencies libvips configure picks up. Otherwise, it looks good!

**Comment by Nakilon** [comment]
I would rather base on image with vips and then integrate it with Lambda in any way you want than vise versa.

**Comment by jcupitt** [comment]
Re. Heroku, there's a useful issue on image_processing about this:

https://github.com/janko/image_processing/issues/32
