### ISSUE TITLE
image.write_to_memory yields different results in different environments

### ISSUE THREAD

**Issue by linkyndy** [libvips/ruby-vips#195]
We need to open an image and write its pixels to memory, so a C library can further process it. We're doing this with the lines below:

```ruby
image = Vips::Image.new_from_file(filename)
pixels_pointer = image.write_to_memory
```

However, it seems that what's written in memory differs per environment. We're testing this on a macOS High Sierra and on an Ubuntu Xenial via Docker, with `vips-8.8.0` and `ruby-vips (2.0.13)`. We've MD5-ed the result of writing to memory:

```
p Digest::MD5.hexdigest(pixels_pointer)
```

and here are the outcomes for both:
* macOS High Sierra: `141e9b6a84f4ca05a7699b33fc0ef808`
* Ubuntu Xenial via Docker: `019a568e40dcc41ac6496da06d29d723`

I have no clue why this is happening and where shall I look further. Any tip would be highly appreciated!

**Comment by jcupitt** [comment]
Hello, it can vary for formats like JPEG. Different decompressors will do things like block smoothing and rounding slightly differently.

I would stick to things like PNG or TIFF if you need exact reproducibility.

**Comment by linkyndy** [comment]
Thanks for your fast answer! Unfortunately, we need to do this for all kinds of images, since our library compares images.

That being said, how can I pinpoint what exactly is behaving differently here? We've also run a Python implementation of this, both on macOS and Ubuntu Xenial via Docker and they yield the same `141e9b6a84f4ca05a7699b33fc0ef808`. Which decompressors are you referring to and also, will this only happen to JPEGs or other formats as well? Sorry for all the (nooby) questions.

**Comment by jcupitt** [comment]
JPEG decompression is not exact -- there are a lot of things you can do slightly differently when you reconstruct the image from the coefficients. You'll find every jpg library will produce a very slightly different image. The IJG libjpeg is probably the most widely used one, but I know of at least five other implementations. Some platforms have hardware decompression, and they will be different again. You'll have the same problem with other lossy formats, like HEIC, or even TIFF with a jpeg compressor.

Instead of comparing md5 hashes, I would subtract the decompressed image from a "gold master", calculate a maximum difference, and check that the max diff is under a threshold. You could look at something like spatial CIELAB if you want to get fancy.

http://scarlet.stanford.edu/~brian/scielab/introduction.html

S-CIELAB is easy to implement in ruby-vips.

**Comment by linkyndy** [comment]
Thanks for the insights! I am not comparing MD5 hashes, I just MD5-ed the pixels so it's easier to follow my point. As I mentioned, the pixels are written to memory, and then get accessed by the C library.

However, I still don't understand how come the Ruby implementation on macOS behaves the same as the Python one on both macOS and Ubuntu Xenial via Docker, but **different** than the Ruby implementation on Ubuntu Xenial via Docker?

Is there a way to see which libraries are used by VIPS in all the 4 scenarios mentioned above? Maybe then it will be easier to pinpoint what exactly causes the differences.

**Comment by jcupitt** [comment]
Perhaps one is using libjpeg-turbo, and the other plain libjpeg? It depends how they've been built and what packages you selected.

**Comment by jcupitt** [comment]
You can also get small differences just changing the flags to your C compiler. `-ffast-math` will change the rounding behaviour of the float path in the IJG library, for example.

**Comment by linkyndy** [comment]
I understand. Thank you very much for all your help. I will analyse and see what's the most appropriate solution to our problem.

**Comment by ioquatix** [comment]
Does vips have a fast image diff algorithm that can return absolute difference, sd, se, etc?

**Comment by jcupitt** [comment]
You could do `(A - B).stats()`, it should be pretty quick and will give you max / min / mean / sdev etc.

**Comment by ioquatix** [comment]
That's awesome, thanks @jcupitt

**Comment by linkyndy** [comment]
Closing this one, thanks for your help, @jcupitt!
