### ISSUE TITLE
Is it possible to save directly to S3 bucket?

### ISSUE THREAD

**Issue by blackpond** [libvips/ruby-vips#205]
When separating a PDF, I'm currently saving to the local file system and then uploading to S3.  Is this the best way to go performance wise, or is it possible to directly upload to S3?

I read the following thread, but couldn't get it to work:
https://github.com/libvips/ruby-vips/issues/27

pseudo code:
```
pages.each_with_index do |page, index|
    page.write_to_file(@page_path)
    upload_page = s3.bucket('mybucket').object("myfile.png")
    upload_page.upload_file("#{upload_path}.png")
end
```

**Comment by jcupitt** [comment]
I guess you want to make a PNG for each page, is that right? You can use `write_to_buffer` to make a string containing the PNG.

PNG write is **very** slow, so that will dominate. Probably nothing else you do will make much difference.

The quickest would be:

```ruby
require 'vips'
  
# n: is the number of pages to load, -1 means all pages in tall, thin image
image = Vips::Image.pdfload ARGV[0], n: -1

# we can get the number of pages and the height of each page from the metadata
n_pages = image.get 'n-pages'
page_height = image.get 'page-height'

# loop down the image cutting it into an array of separate pages
(0 ... n_pages).each do |page_number|
    page = image.crop(0, page_number * page_height, image.width, page_height)
    puts "rendering page #{page_number} ..."
    png_string = page.write_to_buffer ".png"
    # now send the string containing the formatted PNG image off to S3
end
```

That'll only work if every page has the same pixel dimensions. If you can have mixed page sizes, you'll need to do:

```ruby
require 'vips'
  
image = Vips::Image.pdfload ARGV[0]
n_pages = image.get 'n-pages'

(0 ... n_pages).each do |page_number|
    puts "rendering page #{page_number} ..."
    page = Vips::Image.pdfload ARGV[0], page: page_number
    png_string = page.write_to_buffer ".png"
    # now send the string containing the formagtted PNG image off to S3
end
```

Which will be slightly slower.

**Comment by jcupitt** [comment]
Have you tried:

```
$ vipsthumbnail nipguide.pdf[n=-1] -o x.gif
```

Not very useful, but quite fun.

**Comment by jcupitt** [comment]
Issue 27 is for two ruby-vips versions ago, it's all changed a lot since then heh. 

That version was all in C, then we broke the API for vips8 and redid it with gobject-introspection, and now we've redone it all again for plain ffi and libvips' own introspection system, but with the same API as v2.

**Comment by blackpond** [comment]
You where right about png being slow. Jpg sped things up quite a bit.  Thanks for all the great info, I’ll test it all out this weekend!

**Comment by jcupitt** [comment]
libvips 8.9 has a new thing for this: true streaming.

Here's a post introducing it, with Ruby examples:

https://libvips.github.io/libvips/2019/12/11/What's-new-in-8.9.html

You need git master libvips and git master ruby-vips. It should all be released in the next few days.
