### ISSUE TITLE
"Vips::Error: conv: matrix image must have one band" in master

### ISSUE THREAD

**Issue by Nakilon** [libvips/ruby-vips#215]
After few weeks pause I'm again working on my gem running through my rake tasks and now I've found that this piece of code:

```ruby
    def pixelate file, hash_size, kernel
      image = Vips::Image.new_from_file file
      image.resize((hash_size + 1).fdiv(image.width), vscale: hash_size.fdiv(image.height), kernel: kernel).colourspace("b-w")
    end

      image = pixelate file, hash_size, kernel
      image.cast("int").conv([1, -1])
```

throws `Vips::Error: conv: matrix image must have one band` in master branch but works fine in 2.0.12-2.0.16
Commit ba16b13e6f01795303dd13a4045718d8d656c11c was fine. Things broke later.

**Comment by jcupitt** [comment]
Hi @Nakilon,

I had a look and this change is because we fixed `find_inside`.

Now it actually works, `conv` is expanding constants like `[a, b, c]` into images by treating them as pixels, so your `[1, -1]` becomes a two-band image the same size as `image`. 

To make a 2D image from a constant, you need to pass a 2D array, ie.:

```ruby
      image.cast("int").conv([[1, -1]])
```

Will work in 2.0.16 and master.

**Comment by Nakilon** [comment]
Ah, really, this works in both. Thank you.
