### ISSUE TITLE
Crash when calling .to_a twice in a row on same image

### ISSUE THREAD

**Issue by pilaf** [libvips/ruby-vips#330]
I'm using ruby-vips 2.1.4.

```
$ ruby --version
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
```

Using the image below, if I do:

```ruby
im = Vips::Image.thumbnail('gull.jpg', 10)
im.to_a # works
im.to_a # crashes
```

The error message:

```
(process:80152): VIPS-WARNING **: 23:45:23.541: error in tile 0 x 0

(process:80152): VIPS-WARNING **: 23:45:23.541: error in tile 0 x 0

(process:80152): VIPS-WARNING **: 23:45:23.541: error in tile 0 x 0

(process:80152): VIPS-WARNING **: 23:45:23.541: error in tile 0 x 0
/Users/pilaf/.rvm/gems/ruby-3.1.0/gems/ruby-vips-2.1.4/lib/vips/image.rb:701:in `get_bytes': invalid memory read at address=0x0000000000000000 (FFI::NullPointerError)
	from /Users/pilaf/.rvm/gems/ruby-3.1.0/gems/ruby-vips-2.1.4/lib/vips/image.rb:701:in `write_to_memory'
	from /Users/pilaf/.rvm/gems/ruby-3.1.0/gems/ruby-vips-2.1.4/lib/vips/image.rb:1211:in `to_enum'
	from /Users/pilaf/.rvm/gems/ruby-3.1.0/gems/ruby-vips-2.1.4/lib/vips/image.rb:1224:in `to_a'
```

The image:

![gull](https://user-images.githubusercontent.com/38060/157058353-73816e9f-6841-4a81-a8f5-aef654dacb12.jpg)

I can reproduce this consistently on my machine using this image, but it happens also with a few others, generally JPEGs. I wasn't able to reproduce it when loading WebP images instead.

Not sure if this is an actual bug or if I'm doing something wrong.

Thanks for vips BTW!

**Comment by jcupitt** [comment]
Hello @pilaf,

This is by design -- you can only read the output of `thumbnail` once. This is because it runs as a "streaming" operation --- the source image is read, processed, and delivered to the downstream image in a set of small chunks, one after the other. Once you've read the last one, you can't go back and read the first one.

If you really need to read it several times, you must take a copy. Perhaps:

```ruby
im = Vips::Image.thumbnail('gull.jpg', 10).copy_memory()
im.to_a # will works
im.to_a # will also work
```

That'll render the image into a large chunk of memory, then serve request from that. It will obviously be rather expensive for large images.

**Comment by pilaf** [comment]
Hi @jcupitt, thanks a lot for the detailed explanation.

I hope you don't mind a couple follow-up questions:

1. Why would some pictures not have this problem? (as I mentioned, when loading WebP files I'm able to `.to_a` twice without the crash)
2. In actuality I'm loading the image with `.thumbnail`, and then doing some further processing from there. Would the streaming operation cascade all the way down to the last operation? I would assume that's the case because I get the same `.to_a` crash at the end of the pipe. And would `.copy_memory`ing after those other operations also result in high memory usage?

Thank you.

**Comment by jcupitt** [comment]
1. A few loaders (like webp) don't support progressive (chunkwise) loading --- they decode the whole image into memory in one shot. You can read from these repeatedly. Webp does let you load frames of an animation separately at least, so you can't rewind one of those.
2. It's the downsized image that's copied to memory, so memory use probably isn't that high if you use it on the output of thumbnail (unless you are dealing with very large thumbnails). Put another way, `copy_memory` splits a pipeline in two, with everything downstream from it being served from a copy of the image at that point.

(it's not really a crash IMO, just an error because you've asked it to do something it can't do)

**Comment by pilaf** [comment]
Thanks again for the explanations @jcupitt.

You're absolutely right about terminology, I didn't mean to imply libvips was misbehaving, rather used "crash" in the Ruby sense of "unhandled exception".
